# Generated by Django 3.1.4 on 2020-12-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=6, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('observations', models.TextField(verbose_name='Observations')),
                ('people_friendly', models.PositiveIntegerField(verbose_name='People friendly')),
                ('dog_friendly', models.PositiveIntegerField(verbose_name='Dog friendly')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('hair', models.CharField(max_length=10, verbose_name='Hair')),
                ('reason_for_arrival', models.TextField(null=True, verbose_name='Reason for arrival')),
                ('walking_on_leash', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=3, verbose_name='Walking on leash')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
