# Generated by Django 3.1.4 on 2020-12-31 08:12

import adoption.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=6)),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('height', models.PositiveIntegerField()),
                ('observations', models.TextField()),
                ('people_friendly', models.PositiveIntegerField()),
                ('dog_friendly', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('hair', models.CharField(choices=[('l', 'long'), ('m', 'middle'), ('s', 'short')], max_length=6)),
                ('reason_for_arrival', models.TextField(choices=[('1', 'abandoned at the shelter'), ('2', 'injured'), ('3', 'rescued from streets'), ('4', 'other')], null=True)),
                ('photo', models.ImageField(blank=True, upload_to=adoption.models.upload_photo_path)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
