# Generated by Django 3.1.4 on 2021-01-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_data',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='height',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
