# Generated by Django 3.1.4 on 2020-12-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog_data',
            name='walking_on_leash',
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='dog_friendly',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='hair',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='observations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='people_friendly',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dog_data',
            name='reason_for_arrival',
            field=models.TextField(choices=[('1', 'abandoned at the shelter'), ('2', 'injured'), ('3', 'rescued from streets'), ('4', 'other')], null=True),
        ),
    ]
