# Generated by Django 3.1.4 on 2020-12-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_auto_20201228_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog_data',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dog_data',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dog_data',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
